### PR TITLE
laravel versions > 7.1

### PR DESCRIPTION
**Pull request by noud**
mind, the lines are exploding a bit,
given you did not use ^ nor ~ there in the first place.

### CODE REVIEW

**Comment by J87NL** [comment]
@Agontuk @jj-meyer Any chance this could be merged into Master? I have some trouble installing in Laravel 8.

**Comment by noud** [comment]
> @Agontuk @jj-meyer Any chance this could be merged into Master? I have some trouble installing in Laravel 8.

may i have a go?

**Comment by Agontuk** [comment]
Sorry for the delay, I think master branch already supports laravel 7 & 8. Let me know if it works for you, I'll then close the pr.

**Comment by J87NL** [comment]
Both `composer require` and `composer require --dev` have the same error on a fresh Laravel 8:
```
  Problem 1
    - Root composer.json requires agontuk/schema-builder ^1.2 -> satisfiable by agontuk/schema-builder[1.2.0].
    - agontuk/schema-builder 1.2.0 requires illuminate/filesystem 5.1.*|5.2.*|5.3.*|5.4.*|5.5.* -> found illuminate/filesystem[v5.1.1, ..., 5.5.x-dev] but these were not loaded, likely because it conflicts with another require.
```

Tried @noud's [version](https://github.com/noud/schema-builder) this morning, that worked :-)

**Comment by Agontuk** [comment]
> Both `composer require` and `composer require --dev` have the same error on a fresh Laravel 8:
> 
> ```
>   Problem 1
>     - Root composer.json requires agontuk/schema-builder ^1.2 -> satisfiable by agontuk/schema-builder[1.2.0].
>     - agontuk/schema-builder 1.2.0 requires illuminate/filesystem 5.1.*|5.2.*|5.3.*|5.4.*|5.5.* -> found illuminate/filesystem[v5.1.1, ..., 5.5.x-dev] but these were not loaded, likely because it conflicts with another require.
> ```
> 
> Tried @noud's [version](https://github.com/noud/schema-builder) this morning, that worked :-)

Ohh, that's because I forgot to publish it as a new version. You can try the dev-master branch to get the recent changes. I'll publish it tonight.

**Comment by Agontuk** [comment]
v1.3.0 published, let me know if it works for you.

**Comment by noud** [comment]
nice. was just thinking what code to do the evening ;-)

**Comment by J87NL** [comment]
> v1.3.0 published, let me know if it works for you.

Yes, it works :smile:

**Comment by Agontuk** [comment]
Nice, closing this then.

**Pull request closed without merging**
