### PR TITLE
Laravel 7.0 and 7.1

### PR DESCRIPTION
**Pull request by noud**
hi Iftekhar,

sure hope that is your calling name and not family name.

I have 2 diffs to keep running also in Laravel 7.0.* and 7.1.*

That is
the versioning in the composer.json
and str_contains got removed,
and the advise is to use strpos.

Questions more than welcome.

Hope all is fine over there
(especially in these times)

o and excuse i touched the naming
to have it tested through packagist.

thank you,
Noud

### CODE REVIEW

**Comment by Agontuk** [comment]
Hello, sorry for the delayed response. Can you reset the author & github url to previous value ? Also just to make sure, do all the versions you added works with this lib ?

**Comment by noud** [comment]
Iftekhar, no problem at all.
And i will not do this immediate, but real soon.
Maybe of interest to you?https://github.com/noud/erd-js(love to hear
your input/thoughts about this)(and do not look at my code in this, it
is real bad written)
Noud-- On Fri, 2020-08-07 at 00:24 -0700, Iftekhar Rifat wrote:

**Comment by noud** [comment]
On Fri, 2020-08-07 at 00:24 -0700, Iftekhar Rifat wrote:
reset the author & github url to previous value

did i do it again did i.

So much pardon from me to you.

Noud
--

**Comment by Agontuk** [comment]
> Iftekhar, no problem at all. And i will not do this immediate, but real soon.

Sure, take your time.
> Maybe of interest to you?https://github.com/noud/erd-js(love to hear your input/thoughts about this)

Looks cool, nice concept. Keep it going

**Comment by noud** [comment]
i did reset the author & github url to previous values.

**Pull request merged**
