### PR TITLE
Dependencies  update

### PR DESCRIPTION
**Pull request by noud**
hi,

would you be so kind to pull this up.
i needed the changes to work with Laravel 5.8

thanks,
Noud

### CODE REVIEW

**Comment by Agontuk** [comment]
Hello, can you confirm if this change works with previous versions of laravel ? I haven't been using laravel for some time, so don't know about the current changes.

**Comment by noud** [comment]
please let me check this upcoming weekend
i had that thought as well, does it now still work with older versions
(and i am a little afraid, it does not)

**Comment by noud** [comment]
see pull request #6

**Comment by noud** [comment]
Hello as well, them must. I did only add versions, no replacement. And
strpos is PHP 4, PHP 5, PHP 7 it's manual tells us.

On Wed, 2019-09-18 at 22:42 -0700, Iftekhar Rifat wrote:
Hello, can you confirm if this change works with previous versions of laravel ? I haven't been using laravel for some time, so don't know about the current changes.

**Pull request closed without merging**
